from __future__ import annotations

# Product identity
APP_NAME = "TestFabric"
APP_VERSION = "0.1.0"

# Config
DEFAULT_CONTEXT_NAME = "local"
DEFAULT_CONTEXT_MODE_LOCAL = "local"
DEFAULT_CONTEXT_MODE_REMOTE = "remote"

# API / backend
DEFAULT_REMOTE_API_URL = "http://localhost:5678"
DEFAULT_API_TIMEOUT_SECONDS = 30.0
DEFAULT_WORKER_HEARTBEAT_TIMEOUT_SECONDS = 60.0
DEFAULT_WORKER_HEARTBEAT_INTERVAL_SECONDS = 5.0
DEFAULT_WORKER_IDLE_SLEEP_SECONDS = 1.0
DEFAULT_WORKER_CAPACITY = 1
DEFAULT_QUEUE_POLICY = "fifo"
DEFAULT_ARTIFACT_BROWSER_LIMIT = 200
DEFAULT_ARTIFACT_PREVIEW_BYTES = 4096
DEFAULT_ARTIFACT_PREVIEW_LINES = 50
DEFAULT_DB_FILENAME = "testfabric-api-v4.sqlite3"
DEFAULT_EVENT_LIMIT = 100
DEFAULT_EVENT_FOLLOW_TIMEOUT_SECONDS = 30.0
DEFAULT_EVENT_FOLLOW_POLL_INTERVAL_SECONDS = 0.25

# Paths / filenames
DEFAULT_ARTIFACTS_DIR_NAME = "artifacts"
DEFAULT_RUNS_SUBDIR_NAME = "runs"
DEFAULT_WORKERS_TMP_SUBDIR_NAME = "workers_tmp"
DEFAULT_WORKERS_SUBDIR_NAME = "workers"
DEFAULT_WORKER_ID = "w000"
DEFAULT_RUN_SUMMARY_FILENAME = "summary.json"
DEFAULT_EVENTS_FILENAME = "events.jsonl"
DEFAULT_STAGE_SUMMARY_FILENAME = "stage-summary.json"
DEFAULT_COLLECT_SUMMARY_FILENAME = "collect-summary.json"
DEFAULT_DISPATCH_SUMMARY_FILENAME = "dispatch-summary.json"

# Worker / run state labels
RUN_STATE_QUEUED = "queued"
RUN_STATE_RUNNING = "running"
RUN_STATE_COMPLETED = "completed"
RUN_STATE_FAILED = "failed"
RUN_STATE_CANCELED = "canceled"
RUN_STATE_DRY_RUN = "dry-run"

WORKER_STATE_HEALTHY = "healthy"
WORKER_STATE_DEGRADED = "degraded"
WORKER_STATE_UNHEALTHY = "unhealthy"
WORKER_STATE_STALE = "stale"

QUEUE_POLICY_FIFO = "fifo"
QUEUE_POLICY_LIFO = "lifo"
QUEUE_POLICY_PRIORITY = "priority"
QUEUE_POLICY_AFFINITY = "affinity"

AUTH_HEADER_NAME = "Authorization"
AUTH_BEARER_PREFIX = "Bearer "
